# 網站基本設定
title: "Tony 的個人網站"
description: "創業家、內容創作者與專業領域專家"
baseurl: ""
url: "https://tonyonier99.github.io"

# 作者資訊
author:
  name: "Tony"
  email: "your.email@example.com"

# 建置設定
markdown: kramdown
highlighter: rouge
# Remove theme dependency for custom layouts
# theme: minima

# 導航選單
header_pages:
  - about.md
  - blog.md
  - courses.md
  - books.md
  - contact.md

# 社群媒體連結
social_links:
  twitter: your_twitter
  github: tonyonier99
  linkedin: your_linkedin
  instagram: your_instagram
  youtube: your_youtube

# SEO 和功能插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 其他設定
show_excerpts: true
paginate: 5
timezone: Asia/Taipei
lang: zh-TW

# 排除檔案
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# 預設值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tony"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"